[tool.poetry]
name = "mykaggle"
version = "0.1.0"
description = ""
authors = ["cfiken <cfiken@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8.6, <4.0.0"
jupyter = "*"
jupyterlab = "*"
numpy = "*"
matplotlib = "*"
pillow = "*"
pandas = "*"
seaborn = "*"
lightgbm = "*"
tensorflow = "^2.3.1"
tensorflow-addons = "*"
tensorflow-datasets = "*"
transformers = "*"
# torch = {url = "https://download.pytorch.org/whl/cu101/torch-1.6.0%2Bcu101-cp38-cp38-linux_x86_64.whl"}
fastprogress = "*"
kaggle = "*"
pyyaml = "*"
mlflow = "*"
feather-format = "^0.4.0"
jpholiday = "^0.1.1"
matplotlib-venn = "^0.11.5"
pandas-profiling = "*"
boto3 = "*"
python-dotenv = "^0.15.0"
guruguru = "^0.1.1"
texthero = "^1.0.9"


[tool.poetry.dev-dependencies]
pytest = "*"
flake8 = "*"
mypy = "*"
autopep8 = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
