# Python CircleCI 2.0 configuration file
#
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.8.6

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "poetry.lock" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: install dependencies
          command: |
            poetry install 
      - save_cache:
          paths:
            - ./.venv
          key: dependencies-{{ checksum "poetry.lock" }}-{{ checksum ".circleci/config.yml" }}
      - run: 
          name: run tests
          command: |
            poetry run pytest
      - run:
          name: run flake8
          command: |
            poetry run flake8
      - run:
          name: run mypy
          command: |
            poetry run mypy ./ --ignore-missing
  kaggle:
    docker:
      - image: circleci/python:3.8.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "poetry.lock" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: install dependencies
          command: |
            poetry install 
      - run:
          name: zip source
          command: |
            zip -r ./kaggle_datasets_git/mykaggle.zip ./mykaggle
      - run:
          name: upload to kaggle dataset
          command: |
            poetry run kaggle datasets version -p ./kaggle_datasets_git -m $CIRCLE_SHA1 -d
workflows:
  version: 2
  test:
    jobs:
      - test
  kaggle:
    jobs:
      - kaggle:
          filters:
            branches:
              only: master
